[package]
name = "rusty_snake"
version = "0.1.0"
authors = ["Danny"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
piston_window = "0.106.0"
find_folder = "*"
rand = "0.7.3"